### ISSUE TITLE
Диаграмма последовательностей

### ISSUE THREAD

**Issue by AniSkyWorker** [UsingCoding/WebAppArchitecture#3]
- [x] На диаграммах не совсем валидный кейс. С точки зрения сервиса плейлистов - плейлист хранит в себе id контента, а не информацию о нём. Т.е. данные по названиям собирает gateway. Плейлист же должен обновлять инфу именно о наличии контента и проверять, что контент существует, когда его добавляют в плейлист

**Comment by UsingCoding** [comment]
Поправил, в исправленной диаграмме привёл пример другого асинхронного взаимодействия
